/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppFriendsRouteImport } from './routes/app.friends'
import { Route as AppUserFriendIdRouteImport } from './routes/app.user.$friendId'
import { Route as AppStatsFriendIdRouteImport } from './routes/app.stats.$friendId'
import { Route as AppSettingsThemeRouteImport } from './routes/app.settings.theme'
import { Route as AppSettingsSectionRouteImport } from './routes/app.settings.$section'
import { Route as AppChatsChatIdRouteImport } from './routes/app.chats.$chatId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppUserFriendIdRoute = AppUserFriendIdRouteImport.update({
  id: '/user/$friendId',
  path: '/user/$friendId',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsFriendIdRoute = AppStatsFriendIdRouteImport.update({
  id: '/stats/$friendId',
  path: '/stats/$friendId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsThemeRoute = AppSettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsChatIdRoute = AppChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/chats/$chatId': typeof AppChatsChatIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/theme': typeof AppSettingsThemeRoute
  '/app/stats/$friendId': typeof AppStatsFriendIdRoute
  '/app/user/$friendId': typeof AppUserFriendIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/chats/$chatId': typeof AppChatsChatIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/theme': typeof AppSettingsThemeRoute
  '/app/stats/$friendId': typeof AppStatsFriendIdRoute
  '/app/user/$friendId': typeof AppUserFriendIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/chats/$chatId': typeof AppChatsChatIdRoute
  '/app/settings/$section': typeof AppSettingsSectionRoute
  '/app/settings/theme': typeof AppSettingsThemeRoute
  '/app/stats/$friendId': typeof AppStatsFriendIdRoute
  '/app/user/$friendId': typeof AppUserFriendIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/friends'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/chats/$chatId'
    | '/app/settings/$section'
    | '/app/settings/theme'
    | '/app/stats/$friendId'
    | '/app/user/$friendId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/app/friends'
    | '/app/notifications'
    | '/app/profile'
    | '/app'
    | '/app/chats/$chatId'
    | '/app/settings/$section'
    | '/app/settings/theme'
    | '/app/stats/$friendId'
    | '/app/user/$friendId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/onboarding'
    | '/app/friends'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/chats/$chatId'
    | '/app/settings/$section'
    | '/app/settings/theme'
    | '/app/stats/$friendId'
    | '/app/user/$friendId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/user/$friendId': {
      id: '/app/user/$friendId'
      path: '/user/$friendId'
      fullPath: '/app/user/$friendId'
      preLoaderRoute: typeof AppUserFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats/$friendId': {
      id: '/app/stats/$friendId'
      path: '/stats/$friendId'
      fullPath: '/app/stats/$friendId'
      preLoaderRoute: typeof AppStatsFriendIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/theme': {
      id: '/app/settings/theme'
      path: '/settings/theme'
      fullPath: '/app/settings/theme'
      preLoaderRoute: typeof AppSettingsThemeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/$section': {
      id: '/app/settings/$section'
      path: '/settings/$section'
      fullPath: '/app/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/$chatId': {
      id: '/app/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/app/chats/$chatId'
      preLoaderRoute: typeof AppChatsChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFriendsRoute: typeof AppFriendsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsChatIdRoute: typeof AppChatsChatIdRoute
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsThemeRoute: typeof AppSettingsThemeRoute
  AppStatsFriendIdRoute: typeof AppStatsFriendIdRoute
  AppUserFriendIdRoute: typeof AppUserFriendIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFriendsRoute: AppFriendsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsChatIdRoute: AppChatsChatIdRoute,
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsThemeRoute: AppSettingsThemeRoute,
  AppStatsFriendIdRoute: AppStatsFriendIdRoute,
  AppUserFriendIdRoute: AppUserFriendIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
